# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ee2d53ce-1114-49bf-ba71-1f35bc67518d";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ee2d53ce-1114-49bf-ba71-1f35bc67518d";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/ee2d53ce-1114-49bf-ba71-1f35bc67518d";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

  # fmask/dmask are 0077 rather than the generated 0022 so the ESP is readable
  # by root only. With 0022, systemd-boot complains on every single boot:
  #     Mount point '/boot' which backs the random seed file is world
  #     accessible, which is a security hole!
  #     Random seed file '/boot/loader/random-seed' is world accessible, ...
  # The firmware reads the ESP directly and does not care about Linux
  # permissions, so tightening this costs nothing.
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F577-70E8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a4a5f22b-b31a-4e83-a81e-f0740f08377c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
